### PR TITLE
Create winget.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @martinet101.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @martinet101

**Comment by sitiom** [comment]
@vedantmgoyal2009 File is in the wrong folder (It should be in `.github\workflows`)

**Comment by martinet101** [comment]
Yes, git it moved, but it is failing with 404 error?
https://github.com/martinet101/WingetUI/runs/8186370762?check_suite_focus=true

**Comment by sitiom** [comment]
The action is not made to run in a `workflow_dispatch` but in a published release, try rereleasing 1.3 again.

**Comment by martinet101** [comment]
Oh, i see

**Comment by martinet101** [comment]
Yes, now it worked

**Comment by sitiom** [comment]
Is that just a test release or will you actually move the actual `1.3` tag to the latest commit now 😅

**Pull request merged**
